import { PDFDocument, StandardFonts, rgb, PageSizes } from 'pdf-lib'

export interface CertificateData {
  envelopeId: string
  subject: string
  documentHash: string
  senderName: string
  senderEmail: string
  completedAt: Date
  signers: Array<{
    name: string
    email: string
    ipAddress: string
    signedAt: Date
    signatureMethod: string // 'drawn' | 'typed' | 'uploaded'
  }>
  tsaTimestamp?: Date | null
  signatureProfile?: string // e.g. 'CAdES-T'
  auditTrail?: Array<{
    seq: number | null
    event: string
    actorEmail: string | null
    ipAddress: string | null
    createdAt: Date
  }>
  chainHead?: string // the verified chain head hash
}

// Layout constants
const MARGIN_LEFT = 50
const MARGIN_RIGHT = 50
const PAGE_WIDTH = PageSizes.Letter[0] // 612
const PAGE_HEIGHT = PageSizes.Letter[1] // 792
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
const LINE_HEIGHT = 14
const SECTION_GAP = 24

// Colors
const BLACK = rgb(0, 0, 0)
const DARK_GRAY = rgb(0.2, 0.2, 0.2)
const MEDIUM_GRAY = rgb(0.4, 0.4, 0.4)
const LIGHT_GRAY = rgb(0.85, 0.85, 0.85)
const ACCENT = rgb(0.06, 0.09, 0.16) // #0f172a — SwiftSign brand

function formatDate(date: Date): string {
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZoneName: 'short',
    timeZone: 'America/Toronto',
  })
}

function capitalizeMethod(method: string): string {
  if (!method) return 'Unknown'
  return method.charAt(0).toUpperCase() + method.slice(1)
}

/**
 * Generates a Certificate of Completion PDF summarizing the signing event.
 */
export async function generateCertificate(
  data: CertificateData
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create()

  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const courier = await pdfDoc.embedFont(StandardFonts.Courier)

  let page = pdfDoc.addPage(PageSizes.Letter)
  let y = PAGE_HEIGHT - 60
  let pageNum = 1

  // Helper: check if we need a new page
  function ensureSpace(needed: number) {
    if (y - needed < 60) {
      drawFooter()
      page = pdfDoc.addPage(PageSizes.Letter)
      pageNum++
      y = PAGE_HEIGHT - 60
    }
  }

  // Helper: draw footer on current page
  function drawFooter() {
    const footerY = 30
    const footerText = `Generated by SwiftSign on ${formatDate(new Date())}`
    const pageText = `Page ${pageNum}`

    page.drawText(footerText, {
      x: MARGIN_LEFT,
      y: footerY,
      size: 8,
      font: helvetica,
      color: MEDIUM_GRAY,
    })

    const pageTextWidth = helvetica.widthOfTextAtSize(pageText, 8)
    page.drawText(pageText, {
      x: PAGE_WIDTH - MARGIN_RIGHT - pageTextWidth,
      y: footerY,
      size: 8,
      font: helvetica,
      color: MEDIUM_GRAY,
    })
  }

  // Helper: draw a horizontal rule
  function drawRule() {
    page.drawLine({
      start: { x: MARGIN_LEFT, y },
      end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
      thickness: 0.5,
      color: LIGHT_GRAY,
    })
    y -= 12
  }

  // Helper: draw a labeled row (label: value)
  function drawRow(label: string, value: string, options?: { mono?: boolean }) {
    ensureSpace(LINE_HEIGHT + 4)
    const font = options?.mono ? courier : helvetica
    const valueSize = options?.mono ? 8 : 10

    page.drawText(label, {
      x: MARGIN_LEFT,
      y,
      size: 10,
      font: helveticaBold,
      color: DARK_GRAY,
    })

    const labelWidth = helveticaBold.widthOfTextAtSize(label, 10)
    page.drawText(value, {
      x: MARGIN_LEFT + labelWidth + 6,
      y,
      size: valueSize,
      font,
      color: BLACK,
    })

    y -= LINE_HEIGHT + 4
  }

  // ═══════════════════════════════════════════════
  // HEADER
  // ═══════════════════════════════════════════════

  // Brand bar
  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 4,
    width: PAGE_WIDTH,
    height: 4,
    color: ACCENT,
  })

  // Title
  const title = 'CERTIFICATE OF COMPLETION'
  const titleWidth = helveticaBold.widthOfTextAtSize(title, 18)
  page.drawText(title, {
    x: (PAGE_WIDTH - titleWidth) / 2,
    y,
    size: 18,
    font: helveticaBold,
    color: ACCENT,
  })
  y -= 24

  // SwiftSign branding
  const brand = 'SwiftSign \u2014 Electronic Signature Platform'
  const brandWidth = helvetica.widthOfTextAtSize(brand, 10)
  page.drawText(brand, {
    x: (PAGE_WIDTH - brandWidth) / 2,
    y,
    size: 10,
    font: helvetica,
    color: MEDIUM_GRAY,
  })
  y -= SECTION_GAP

  drawRule()

  // ═══════════════════════════════════════════════
  // DOCUMENT INFORMATION
  // ═══════════════════════════════════════════════

  page.drawText('Document Information', {
    x: MARGIN_LEFT,
    y,
    size: 14,
    font: helveticaBold,
    color: ACCENT,
  })
  y -= 20

  drawRow('Envelope ID:', data.envelopeId)
  drawRow('Subject:', data.subject)
  drawRow('Status:', 'Completed')
  drawRow('Completed:', formatDate(data.completedAt))
  drawRow('Document Hash (SHA-256):', data.documentHash, { mono: true })

  y -= 8
  drawRule()

  // ═══════════════════════════════════════════════
  // SENDER INFORMATION
  // ═══════════════════════════════════════════════

  ensureSpace(80)

  page.drawText('Sender', {
    x: MARGIN_LEFT,
    y,
    size: 14,
    font: helveticaBold,
    color: ACCENT,
  })
  y -= 20

  drawRow('Name:', data.senderName)
  drawRow('Email:', data.senderEmail)

  y -= 8
  drawRule()

  // ═══════════════════════════════════════════════
  // SIGNER DETAILS
  // ═══════════════════════════════════════════════

  ensureSpace(40)

  page.drawText('Signer Details', {
    x: MARGIN_LEFT,
    y,
    size: 14,
    font: helveticaBold,
    color: ACCENT,
  })
  y -= 20

  for (let i = 0; i < data.signers.length; i++) {
    const signer = data.signers[i]

    // Each signer block needs ~90px
    ensureSpace(100)

    // Signer header with background
    page.drawRectangle({
      x: MARGIN_LEFT,
      y: y - 4,
      width: CONTENT_WIDTH,
      height: 18,
      color: rgb(0.95, 0.95, 0.97),
    })

    page.drawText(`Signer ${i + 1}`, {
      x: MARGIN_LEFT + 8,
      y,
      size: 11,
      font: helveticaBold,
      color: ACCENT,
    })
    y -= 22

    drawRow('Name:', signer.name)
    drawRow('Email:', signer.email)
    drawRow('Signed At:', formatDate(signer.signedAt))
    drawRow('IP Address:', signer.ipAddress)
    drawRow('Signature Method:', capitalizeMethod(signer.signatureMethod))

    y -= 8

    if (i < data.signers.length - 1) {
      // Subtle separator between signers
      page.drawLine({
        start: { x: MARGIN_LEFT + 20, y: y + 4 },
        end: { x: PAGE_WIDTH - MARGIN_RIGHT - 20, y: y + 4 },
        thickness: 0.3,
        color: LIGHT_GRAY,
      })
      y -= 4
    }
  }

  y -= 8
  drawRule()

  // ═══════════════════════════════════════════════
  // LEGAL NOTICE
  // ═══════════════════════════════════════════════

  ensureSpace(120)

  page.drawText('Legal Notice', {
    x: MARGIN_LEFT,
    y,
    size: 14,
    font: helveticaBold,
    color: ACCENT,
  })
  y -= 20

  const legalLines = [
    'This document was signed electronically via SwiftSign (swiftsign.ca).',
    '',
    'Electronic signatures are legally binding under the Electronic Commerce Act',
    '(Ontario), the ESIGN Act (United States), and the Uniform Electronic',
    'Transactions Act (UETA).',
    '',
    'Document integrity verified via SHA-256 cryptographic hash. The hash above',
    'can be used to verify that this document has not been altered after signing.',
    '',
    'This Certificate of Completion provides a complete audit trail of the',
    'electronic signing process, including signer identity, timestamp, and',
    'IP address for each participant.',
  ]

  for (const line of legalLines) {
    ensureSpace(LINE_HEIGHT)
    if (line === '') {
      y -= 6
      continue
    }
    page.drawText(line, {
      x: MARGIN_LEFT,
      y,
      size: 9,
      font: helvetica,
      color: DARK_GRAY,
    })
    y -= LINE_HEIGHT
  }

  // ═══════════════════════════════════════════════
  // DIGITAL SIGNATURE
  // ═══════════════════════════════════════════════

  const isCadesT = data.signatureProfile === 'CAdES-T'

  if (data.signatureProfile && data.signatureProfile !== 'unsigned') {
    y -= 8
    drawRule()

    ensureSpace(80)

    page.drawText('Digital Signature', {
      x: MARGIN_LEFT,
      y,
      size: 14,
      font: helveticaBold,
      color: ACCENT,
    })
    y -= 20

    const sigLines = isCadesT
      ? [
          'This document carries a PAdES (PKCS#7/CAdES-T) digital signature with',
          'an RFC-3161 trusted timestamp, applied over the final sealed bytes.',
        ]
      : [
          'This document carries a PAdES (PKCS#7/CAdES) digital signature applied',
          'over the final sealed bytes.',
        ]

    for (const line of sigLines) {
      ensureSpace(LINE_HEIGHT)
      page.drawText(line, {
        x: MARGIN_LEFT,
        y,
        size: 9,
        font: helvetica,
        color: DARK_GRAY,
      })
      y -= LINE_HEIGHT
    }

    y -= 6
    drawRow('Signature Profile:', data.signatureProfile)
    if (isCadesT && data.tsaTimestamp) {
      drawRow('Trusted Timestamp (TSA):', formatDate(data.tsaTimestamp))
    }
  }

  // ═══════════════════════════════════════════════
  // AUDIT TRAIL
  // ═══════════════════════════════════════════════

  if (data.auditTrail && data.auditTrail.length > 0) {
    y -= 8
    drawRule()

    ensureSpace(60)

    page.drawText('Audit Trail', {
      x: MARGIN_LEFT,
      y,
      size: 14,
      font: helveticaBold,
      color: ACCENT,
    })
    y -= 20

    for (const entry of data.auditTrail) {
      ensureSpace(LINE_HEIGHT + 2)
      const seqLabel = entry.seq != null ? `#${entry.seq}` : '#—'
      const meta = [
        entry.actorEmail ?? '—',
        entry.ipAddress ?? '—',
        formatDate(entry.createdAt),
      ].join('  •  ')

      page.drawText(`${seqLabel}  ${entry.event}`, {
        x: MARGIN_LEFT,
        y,
        size: 9,
        font: helveticaBold,
        color: DARK_GRAY,
      })
      y -= LINE_HEIGHT - 2

      ensureSpace(LINE_HEIGHT)
      page.drawText(meta, {
        x: MARGIN_LEFT + 12,
        y,
        size: 8,
        font: helvetica,
        color: MEDIUM_GRAY,
      })
      y -= LINE_HEIGHT
    }

    if (data.chainHead) {
      y -= 4
      ensureSpace(LINE_HEIGHT)
      page.drawText('Chain head:', {
        x: MARGIN_LEFT,
        y,
        size: 9,
        font: helveticaBold,
        color: DARK_GRAY,
      })
      const chainLabelWidth = helveticaBold.widthOfTextAtSize('Chain head:', 9)
      page.drawText(data.chainHead, {
        x: MARGIN_LEFT + chainLabelWidth + 6,
        y,
        size: 7,
        font: courier,
        color: BLACK,
      })
      y -= LINE_HEIGHT
      ensureSpace(LINE_HEIGHT)
      page.drawText('Verify at swiftsign.ca/verify', {
        x: MARGIN_LEFT,
        y,
        size: 8,
        font: helvetica,
        color: MEDIUM_GRAY,
      })
      y -= LINE_HEIGHT
    }
  }

  // ═══════════════════════════════════════════════
  // FOOTER on last page
  // ═══════════════════════════════════════════════

  drawFooter()

  // Serialize
  const bytes = await pdfDoc.save()
  return Buffer.from(bytes)
}
