import { getOpenApiDocument } from '@/lib/openapi/registry'
const d = getOpenApiDocument()
console.log('openapi:', d.openapi)
console.log('title:', d.info.title, d.info.version)
console.log('servers:', JSON.stringify(d.servers))
const paths = Object.keys(d.paths || {})
console.log('paths:', paths.length)
paths.forEach((p) => console.log('  ' + p))
console.log('securitySchemes:', Object.keys((d.components as any)?.securitySchemes || {}))
console.log('Problem component:', !!(d.components as any)?.schemas?.Problem)
